# POST http://localhost:3000/api/items
# Content-Type: application/json

# {
#     "item": "3 todo item"
# }

# PUT http://localhost:3001/api/item/6390400361dbd31554f0b289
# Content-Type: application/json

# {     
#     "completed": false
# }